# Generated by Django 4.1.1 on 2022-09-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_image_alter_category_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(default=False, max_length=500),
        ),
    ]
