# Generated by Django 4.1.1 on 2022-10-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_meta_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_prince',
            new_name='selling_price',
        ),
    ]
